### PR TITLE
Release 0.4.0

### PR DESCRIPTION
**Pull request by n1hility**

### CODE REVIEW

**Comment by n1hility** [comment]
@mheon Not sure if you were staging a release for @bgilbert with @baude away, or wanted me to push one up. Approve if you'd like to me to cut the tag and upload the binary. Otherwise, feel free to close and take over.

Thanks!

**Comment by mheon** [comment]
@n1hility Please feel free, I had not coordinated with @baude on this before he left. Approving!

**Review by mheon — APPROVED** [review]

**Comment by n1hility** [comment]
cool will do /lgtm

**Pull request merged**
